[package]
name = "notification"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.13.0"
async-trait = "0.1.89"
sqlx = { version = "0.8.6", features = ["sqlite"] }
serde = "1.0.228"
uuid = "1.23.1"
chrono = { version = "0.4.44", features = ["serde"] }
actixutils = { path = "../actixutils" }
emailgrid = { path = "../emailgrid" }
push={path="../push"}
event-stream = { path = "../event-stream" }
mgk = { path = "../mgk" }
